# Generated by Django 4.2.7 on 2023-12-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
