# Generated by Django 4.2.7 on 2023-12-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_rename_total_price_order_total_bill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
